# Generated by Django 5.0.6 on 2024-07-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_terbit', models.CharField(max_length=20, unique=True)),
                ('no_kk', models.CharField(max_length=20, unique=True)),
                ('nama_kepala', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=4)),
                ('rw', models.CharField(max_length=4)),
                ('kelurahan', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=10)),
                ('provinsi', models.CharField(max_length=50)),
                ('tanggal_dikeluarkan', models.DateField()),
                ('ka_dinas', models.CharField(default='PERSONS 1', max_length=50)),
                ('jumlah_anggota_keluarga', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('graduate', models.CharField(max_length=10)),
                ('passport', models.CharField(max_length=50, unique=True)),
                ('permit', models.CharField(max_length=50, unique=True)),
                ('head_family_name', models.CharField(max_length=100)),
                ('marriage', models.CharField(max_length=50)),
                ('status_in_family', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.familycard')),
            ],
        ),
    ]
