# Generated by Django 5.0.6 on 2024-07-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartuKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_terbit', models.CharField(max_length=20, unique=True)),
                ('no_kk', models.CharField(max_length=20, unique=True)),
                ('nama_kepala', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=4)),
                ('rw', models.CharField(max_length=4)),
                ('kelurahan', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=10)),
                ('provinsi', models.CharField(max_length=50)),
                ('tanggal_dikeluarkan', models.DateField()),
                ('poto', models.ImageField(null=True, upload_to='media/')),
                ('ka_dinas', models.CharField(default='PERSONS 1', max_length=50)),
                ('jumlah_anggota_keluarga', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KartuTandaPenduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(max_length=50)),
                ('pendidikan', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('pernikahan', models.CharField(max_length=50)),
                ('status_keluarga', models.CharField(max_length=100)),
                ('kewarganegaraan', models.CharField(max_length=50)),
                ('passpor', models.CharField(max_length=50, null=True)),
                ('kitas', models.CharField(max_length=50, null=True)),
                ('nama_ayah', models.CharField(max_length=50)),
                ('nama_ibu', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.kartukeluarga')),
            ],
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='FamilyCard',
        ),
    ]
