# Generated by Django 5.0.6 on 2024-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_kartukeluarga_kartutandapenduduk_delete_citizen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartukeluarga',
            name='seri_terbit',
            field=models.CharField(max_length=20),
        ),
    ]
